"""
The sequence of triangle numbers is generated by adding the natural numbers. So the
7th triangle number would be 0 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
    1  : 1
    3  : 1,3
    6  : 1,2,3,6
    10 : 1,2,5,10
    15 : 1,3,5,15
    21 : 1,3,7,21
    28 : 1,2,4,7,14,28

We can see that 28
is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""
def triangle(n:int):
    return int(n*(n + 1)/2)

def primeFactors(n:int):
    import math
    prime:dict[int,int] = {};
    while n%2 == 0:
        if 2 in prime:
            prime[2] += 1
        else:
            prime[2] = 1
        n = int(n/2)

    for i in range(3, int(math.sqrt(n))+1, 2):
        while n%i == 0:
            if i in prime:
                prime[i] += 1
            else:
                prime[i] = 1
            n = int(n/i)
    if n > 1:
        prime[n] = 1
    return prime

def divisors(n:int):
    factors = primeFactors(n)
    divisors = 1;
    for power in factors.values():
        divisors *= (power + 1)
    return divisors

def test():
    import sys
    for i in range(1, len(sys.argv)):
        number = triangle(int(sys.argv[i]))
        factors = divisors(number)
        print(i, ":",number,factors)

if __name__ == "__main__":
    trint = 1
    factors =  0
    while factors < 500:
        trint += 1
        number = triangle(trint)
        factors = divisors(number)
        print(trint,number,factors)
    number = triangle(trint)
    print(trint, number, divisors(number))
